### ISSUE TITLE
Tecnología a aplicar y analisis de mercado

### ISSUE THREAD

**Issue by dancorfon** [ISPP-Grupo-10/cocemfe-sevilla#10]
### Descripción del Documento

Se elaborará un documento acerca de la tecnología que se aplicará para el desarrollo del producto, además se estudiará diferentes alternativas ya en uso en el mercado con posibilidad de aplicar en el proyecto con la finalidad de hacer uso de funcionalidad ya existente.

**Comment by rauulhernaan** [comment]
Documento realizado
