### ISSUE TITLE
LOGIN

### ISSUE THREAD

**Issue by eloyjm** [ISPP-Grupo-10/cocemfe-sevilla#116]
### Describe la funcionalidad.

Funcionalidad y pantalla de login.
FECHA LÍMITE: 09/03/2024

### Describe la solución que te gustaría.

-Inicio de sesión mediante correo electrónico y contraseña. 

-Si no estas logueado, no puedes hacer NADA más que el login.

**Comment by Gonriblu** [comment]
¿El usuario no podrá loguearse con otra cosa que no sea el email?

**Comment by eloyjm** [comment]
> ¿El usuario no podrá loguearse con otra cosa que no sea el email?

En principio no. Si en un futuro se considera oportuno el login mediante username - password, se creará una issue para habilitarlo.
