### ISSUE TITLE
Problemas al iniciar sesión

### ISSUE THREAD

**Issue by eloyjm** [ISPP-Grupo-10/cocemfe-sevilla#118]
### Describe la funcionalidad.

Desde la pantalla de login, se implementará un botón que permita a un usuario describir y enviar un texto al administrador.
El administrador debe tener un panel con los mensajes generados por los usuarios para poder visualizarlos.
FECHA LIMITE: 16/03/2024

**Comment by Gonriblu** [comment]
Entiendo que estos mensajes se realizan por usuarios que tienen problemas con el loggueo, por lo que no estaran loggueados y el formulario incluira su email y una descripcion del problema
