### ISSUE TITLE
[Feature] Notificación: Cambio de estado de documento

### ISSUE THREAD

**Issue by eloyjm** [ISPP-Grupo-10/cocemfe-sevilla#122]
### Describe la funcionalidad.

Se mandará un e-mail a los revisores de dicho documento cada vez que el documento cambie de estado.  
FECHA LIMITE: 16/03/2024

**Comment by ferbaqfer** [comment]
En esta tarea también se contempla el estudio y búsqueda de un algoritmo eficiente para el envío de correos electrónicos.

**Comment by ferbaqfer** [comment]
También se contempla la creación de un correo electrónico de prueba para el desarrollo de la funcionalidad de Notificaciones.
