### ISSUE TITLE
Creación de un profesional (Backend)

### ISSUE THREAD

**Issue by ferbaqfer** [ISPP-Grupo-10/cocemfe-sevilla#134]
## Fecha límite: 09/03/2024
Desarrollar la funcionalidad para crear un profesional.

### Describe la solución que te gustaría.

Se le deberá asignar los siguientes campos:
- Usuario, nombre, apellidos, email, teléfono, n colegiado, organización (fk)
- Al crear un profesional, se le debe asignar una (solo una) organización existente. 

Al crear un profesional, se genera una contraseña automáticamente, la cual se le enviará un email de bienvenida con las credenciales (otra tarea, coordinarse con grupo asignado a notificaciones)

**Comment by JesusSolisOrtega** [comment]
Dado que la tarea de testing se a asignado a otro compañero del mismo grupo, se ha añadido un testing inicial que aunque aún presenta algunos fallos se espera que le ahorre trabajo (la idea es colaborar con el en la creación de los mismos si es posible).

**Comment by tcabgom** [comment]
De acuerdo, muchas gracias. Procedo a retomar el trabajo de las pruebas

**Comment by JesusSolisOrtega** [comment]
Según me ha informado otro compañero parte de los problemas que daba en el testing de la funcionalidad eran derivados de cómo está configurado el uso de contraseñas. 
- Se debe investigar la forma adecuada de gestionar las contraseñas en la creación.

**Comment by JesusSolisOrtega** [comment]
Ha habido numerosos conflictos que solucionar. Lo cual ha retrasado significativamente el avance de la tarea.
- En futuras ocasiones debería mejorarse la comunicación para no trabajar sobre archivos en los que otro compañero tiene cambios en progreso.

**Comment by tcabgom** [comment]
Efectivamente, hemos estado una hora intentando solucionar los fallos.

Ya funciona la creación de usuarios

**Comment by tcabgom** [comment]
He eliminado los mensajes que generan y no servian para nada de la view de crear profesionales, porque si no los tests no funcionaban porque decía que faltaba un middleware el cual he comprobado que está presente en el settings.py
