### ISSUE TITLE
[Feature] Repaso de restricciones de acceso

### ISSUE THREAD

**Issue by eloyjm** [ISPP-Grupo-10/cocemfe-sevilla#135]
### Describe la funcionalidad.

Verificar los accesos y permisos a la hora de mostrar o no botones y funcionalidades por pantalla.

### Describe la solución que te gustaría.

Se deberán seguir las especificaciones dadas en los documentos.

**Comment by Gonriblu** [comment]
- Si quereis que una funcion del view solo pueda ser ejecutada por un administrador, importais 
from professionals.views import is_admin
from django.contrib.auth.decorators import user_passes_test

y poneis el decorador encima de la funcion
@user_passes_test(is_admin)

- Si quereis que se ejecute solo si estais logueados
from django.contrib.auth.decorators import login_required

@login_required
