### ISSUE TITLE
Buscar profesionales con filtros

### ISSUE THREAD

**Issue by ferbaqfer** [ISPP-Grupo-10/cocemfe-sevilla#136]
### Describe la funcionalidad.

Crear un buscador con los siguientes filtros:
- nombre
- apellidos
- n colegiado
- organización

### Describe la solución que te gustaría.

Revisar filtrado de documentos y hacerlo igual si se considera oportuno

**Comment by Ignarrman** [comment]
Esta funcionalidad ya la desarrollamos en el Sprint 1 pero es verdad que el frontend no sigue el mismo estilo que el filtro que aparece en documentos y tengo entendido que otro subgrupo es el que se encarga de unificar los estilos de frontend. Qué hacemos con la issue entonces?

**Comment by eloyjm** [comment]
Tienes razón, voy a cerrarla ya que la funcionalidad en sí esta hecha. El estilo corresponde a otra issue.
