### ISSUE TITLE
[Feature] Creación Profesional (Frontend)

### ISSUE THREAD

**Issue by Ignarrman** [ISPP-Grupo-10/cocemfe-sevilla#166]
### Describe la funcionalidad.

Añade estilos al formulario de creación de profesional.

### Describe la solución que te gustaría.

Utilizar los mismos estilos que creación de documento y organización.

**Comment by JesusSolisOrtega** [comment]
Mi participación en la tarea ha sido solo ayudar a nacho con el tratamiento de las contraseñas: 
- Hemos detectado un error en la populación y el tratamiento de contraseñas.

**Comment by Ignarrman** [comment]
Al que le toque cambiarlo tiene que quitar la contraseña en texto plano y poner el resultado de hacerle el hash.
