### ISSUE TITLE
[Feature] Implementación de analizador de código.

### ISSUE THREAD

**Issue by andressomoza** [ISPP-Grupo-10/cocemfe-sevilla#196]
### Describe la funcionalidad.

Implementar algún analizador de código.

### Describe la solución que te gustaría.

No procede.

### Contexto Adicional

No procede.

**Comment by tcabgom** [comment]
Ha sido necesario hacer commit a main para hacer la tarea.

Gracias a Antonio Pelaez por hacer la configuración desde ubuntu, nosotros no lo teníamos
