### ISSUE TITLE
[Feature] Validación de emails

### ISSUE THREAD

**Issue by Ignarrman** [ISPP-Grupo-10/cocemfe-sevilla#250]
### Describe la funcionalidad.

Implementar una política de validación de emails.

### Describe la solución que te gustaría.

Probar primero un sistema de validación que no incluya una API pero no es posible usar una.
La solución sin API es que se mande un correo para verificar cuenta para que sus usuario creado pase a estar activo.
En caso de usar una Api usaremos alguna como Abstract (Se especificará en la PR)

**Comment by JesusSolisOrtega** [comment]
Mergeado correctamente a Develop, procedo a cerrar la issue como resuelta.
