### ISSUE TITLE
Posibles compradores y nuevas funcionalidades 

### ISSUE THREAD

**Issue by antoniopelaezmoreno** [ISPP-Grupo-10/cocemfe-sevilla#27]
### Descripción del Documento

Se debe hacer un análisis de posibles empresas u otras ONGs que puedan estar interesadas en adquirir la aplicación.
También se debe hacer una lista de nuevos requisitos a proponerle a COCEMFE

**Comment by rauulhernaan** [comment]
Se realizó para la entrega 1
