### ISSUE TITLE
[Bug] Mapa no renderiza en pythonanywhere

### ISSUE THREAD

**Issue by eloyjm** [ISPP-Grupo-10/cocemfe-sevilla#292]
### Descripción del Error

El mapa no renderiza, aunque en local si funcione correctamente. Parece problema de js.

### Pasos para Reproducir

1. Abrir pantalla de mapa

**Comment by ferbaqfer** [comment]
Motivo del bug:
- Se ha intentado poner un script como ubicación del documento, lo que hace que el mapa no pueda renderizar la solicitud.
