### ISSUE TITLE
[Documentation] Añadir a documentos de costes los costes de la seguridad social

### ISSUE THREAD

**Issue by andressomoza** [ISPP-Grupo-10/cocemfe-sevilla#306]
### Descripción del Documento

Añadir a documentos de costes los costes de la seguridad social

### Contexto Adicional

Herramienta recomendada: https://factorialhr.es/calculadora-coste-trabajador
https://www.billin.net/calculadora-contratar-trabajador/

**Comment by dancorfon** [comment]
Ya esta realizada
