### ISSUE TITLE
Commitment agreement (actualizar)

### ISSUE THREAD

**Issue by PabloPinMat** [ISPP-Grupo-10/cocemfe-sevilla#47]
### Descripción del Documento

Actualizar la plantilla: **Plantilla - Compromiso de Participación en la asignatura ISPP v1.1** con los nuevos compromisos establecidos por el equipo en su conjunto, así como las tareas a realizar en el Sprint 1.

**Comment by rauulhernaan** [comment]
Plantilla actualizada por Maqueda
